# Generated by Django 5.0 on 2023-12-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolipapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
